# Generated by Django 4.1 on 2024-11-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_images_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
